Remove 'Add Data' button if all 4 metadata fields are used in Edit Profile
tuskyapp/Tusky pull request #1934
Opened 2020-09-12 17:39 UTC by duggalsu

2020-09-13 00:07 UTC, JuanjoSalvador approved these changes

2020-09-14 05:51 UTC, connyduck requested changes

2020-09-14 05:51 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/EditProfileActivity.kt
> +                it.isVisible = false
Please delete the `it.isEnabled = false`, its not needed when the button is invisible anyway

2020-09-14 08:39 UTC, connyduck approved these changes

2020-09-14 08:39 UTC, merged