Change characters left color to red when negative
tuskyapp/Tusky pull request #1952
Opened 2020-10-04 11:49 UTC by clasick

Implements request by @Porrumentzio in #1594 

The remaining character length indicator in the compose screen turns red when the message exceeds the limit.

### Additional Context
<img src="https://user-images.githubusercontent.com/13066221/95014585-78052a00-0665-11eb-86cb-f9fd18778617.gif" width="300" height="500">

2020-10-04 18:10 UTC, Porrumentzio commented
Great work! What about making it also bold?

2020-10-07 15:59 UTC, connyduck requested changes

2020-10-07 15:59 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
> +        var remainingLength = maximumTootCharacters - calculateTextLength();
can be `val`

2020-10-07 15:59 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
> +            val textColor = ThemeUtils.getColor(this, android.R.attr.colorError)
Field requires API level 26 (current min is 21): `android.R.attr#colorError` - better define your own color, ideally one for the dark themes and one for the light theme

2020-10-07 15:59 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
> +        }
You can write this a bit shorter:
```suggestion
        val textColor = if(remainingLength < 0) {
            ThemeUtils.getColor(this, android.R.attr.colorError)
        } else {
            ThemeUtils.getColor(this, android.R.attr.textColorTertiary)
        }
        composeCharactersLeftView.setTextColor(textColor)
```

2020-10-07 22:02 UTC, clasick commented
Added the changes suggested by @connyduck. The new `tusky_red` color has been defined. I thought it looked fine the way it is on both Night & Day themes as is. Your thoughts?
### Day
![image](https://user-images.githubusercontent.com/13066221/95392266-14555800-0916-11eb-825a-cfd216327012.png)
### Night
![image](https://user-images.githubusercontent.com/13066221/95392329-32bb5380-0916-11eb-9f26-f98fb60c4e0a.png)

2020-10-08 07:24 UTC, Porrumentzio commented
It is good this way. Maybe it's too aggressive in color, but it's a tiny detail.

If it's easy to make, I would like to see it in bold

2020-10-08 19:09 UTC, clasick commented
> It is good this way. Maybe it's too aggressive in color, but it's a tiny detail.
> 
> If it's easy to make, I would like to see it in bold!
> 
> And thanks for the work :)

Yeah, I thought the same myself. The red might be a bit too bright in the Light theme. Could someone suggest a color hex code for the Light one and the Dark one too perhaps? 

I think we can decide first on the exact color to be used and then try making it bold, cause that might alter the perception of the color a bit.

2020-10-09 12:06 UTC, Porrumentzio commented
This colour is which Twitter uses: #DF1553 (more or less)
I would also try this one: #CC1900

2020-10-12 19:25 UTC, clasick commented
Here's the different combinations with those two color codes with their normal/bold variance.
# Normal
## DF1553
### Dark 
![image](https://user-images.githubusercontent.com/13066221/95781687-fb6cee00-0ceb-11eb-9ffd-9933bc98958f.png)
### Light
![image](https://user-images.githubusercontent.com/13066221/95781828-396a1200-0cec-11eb-8209-e90fe45248da.png)
## CC1900
### Dark
![image](https://user-images.githubusercontent.com/13066221/95782071-ada4b580-0cec-11eb-9201-d9e112581d89.png)
### Light
![image](https://user-images.githubusercontent.com/13066221/95782041-9960b880-0cec-11eb-9219-622fc80de278.png)

# Bold
## DF1553
### Dark 
![image](https://user-images.githubusercontent.com/13066221/95783019-9bc41200-0cee-11eb-8340-76f5b5808ae7.png)
### Light
![image](https://user-images.githubusercontent.com/13066221/95782970-87801500-0cee-11eb-8894-eb90a4600338.png)
## CC1900
### Dark
![image](https://user-images.githubusercontent.com/13066221/95782880-4be54b00-0cee-11eb-921d-f2e4bac02569.png)
### Light
![image](https://user-images.githubusercontent.com/13066221/95782914-615a7500-0cee-11eb-87ba-7f083c065887.png)

Personally, I think bold #DF1553 variants look pretty good.

2020-10-12 19:42 UTC, Porrumentzio commented
I also think same way. It looks clearer and less aggressive; and although it really is more pink/purple, it looks red :)

2020-10-13 16:30 UTC, merged