[needs help] Supports announcements
tuskyapp/Tusky pull request #1977
Opened 2020-11-04 15:59 UTC by kyori19

Closes #1693 

Drawer(with one unread announcement)
![Screenshot_1604504702](https://user-images.githubusercontent.com/27999567/98132795-27048200-1f00-11eb-9a7a-95446b80025d.png)
AnnouncementsActivity(with emoji picker opened)
![Screenshot_1604504421](https://user-images.githubusercontent.com/27999567/98132244-81511300-1eff-11eb-8cbb-1d32abad3d11.png)

## Problems

- [ ] No method to add normal emojis (like 🤔 and 👍). We have to add it in emoji picker but it should be really hard work... (Related to #1956). Or add text field for now?
- [ ] Hard to distinguish self reaction. I tried to fix this but couldn't do... (In screenshot above, 🤔 is not selected while 🦀 is selected)
- [ ] Weird chip size in custom emojis. Maybe bug of `emojify` method...? (This custom emoji is `:javascript:`. I think the width is calculated with shortcode.)
![image](https://user-images.githubusercontent.com/27999567/98133226-aeea8c00-1f00-11eb-9519-3c27272e46a8.png)
- [ ] Calling `load()` method after updated reaction(AnnouncementsViewModel L89, L99).  I should call `mutableAnnouncements.postValue` with updated reaction, but it requires deep copy of announcements so I gave up. Should I fix this?
- [ ] Unread announcements badge in the drawer is not appealing. Maybe it should be displayed with colored background, or a badge on drawer toggle button...?
- [ ] When to mark as read announcements. When the user opened AnnouncementsActivity...? Do you have any ideas?

2020-11-05 19:26 UTC, connyduck commented
> No method to add normal emojis (like 🤔 and 👍). We have to add it in emoji picker but it should be really hard work... (Related to #1956). Or add text field for now?

I think is fine if we add this functionality later

> Hard to distinguish self reaction. I tried to fix this but couldn't do... (In screenshot above, 🤔 is not selected while 🦀 is selected)

Yes. Needs a custom chip style. https://material.io/develop/android/components/chips#theming-chips

> Weird chip size in custom emojis. Maybe bug of emojify method...? (This custom emoji is :javascript:. I think the width is calculated with shortcode.)

Oh, this is a hard one. Seems like the width is indeed calculated with the shortcode. No idea how to fix it, but I can investigate further when I have more time. A workaround could be using a different shortcode.

> Calling load() method after updated reaction(AnnouncementsViewModel L89, L99). I should call mutableAnnouncements.postValue with updated reaction, but it requires deep copy of announcements so I gave up. Should I fix this?

Yes, you should. Try something like that

```
 announcementsMutable.value?.data?.map { announcement ->
            if (announcement.id == announcementId) {
                announcement.copy(
                    reactions = announcement.reactions.map { reaction ->
                        if( reaction.name == name) {
                            reaction.copy(count = reaction.count++)
                        } else { 
                            reaction
                        }
                    }
                )
            } else {
                announcement
            }
```

> Unread announcements badge in the drawer is not appealing. Maybe it should be displayed with colored background, or a badge on drawer toggle button...?

Yes. I think white on Tusky blue or background color on primary text color could look cool. You can add a `BadgeStyle` to the drawer item to achieve that. See https://github.com/mikepenz/MaterialDrawer/

> When to mark as read announcements. When the user opened AnnouncementsActivity...? Do you have any ideas?

After opening the activity should be fine. Or add a button in the toolbar "mark all as read". But thats already more effort than necessary.


Another thing I would change is the position in the drawer. I think it is pretty important, it could easily be higher up, maybe even after "edit profile".

Thoughts? @mal0ki @Tak @charlag

2020-11-06 06:37 UTC, kyori19 commented
> > Calling load() method after updated reaction(AnnouncementsViewModel L89, L99). I should call mutableAnnouncements.postValue with updated reaction, but it requires deep copy of announcements so I gave up. Should I fix this?
> 
> Yes, you should. Try something like that

Updated my code, but I have to get emoji's url from emojis so it became bit longer.

2020-11-06 06:48 UTC, kyori19 commented
> > Hard to distinguish self reaction. I tried to fix this but couldn't do... (In screenshot above, 🤔 is not selected while 🦀 is selected)
> 
> Yes. Needs a custom chip style. https://material.io/develop/android/components/chips#theming-chips

I read [this](https://stackoverflow.com/questions/51089150/set-com-google-android-material-chip-chip-selected-color) and I tried to add custom style like this but there's no effect.
Am I something wrong?

```
--- a/app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt
+++ b/app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt
@@ -69,7 +69,7 @@ class AnnouncementAdapter(
 
             item.reactions.forEachIndexed { i, reaction ->
                 (chips.getChildAt(i)?.takeUnless { it.id == R.id.addReactionChip } as Chip?
-                        ?: Chip(ContextThemeWrapper(view.context, R.style.Widget_MaterialComponents_Chip_Choice)).apply {
+                        ?: Chip(ContextThemeWrapper(view.context, R.style.ColoredChip)).apply {
                             isCheckable = true
                             checkedIcon = null
                             chips.addView(this, i)

diff --git a/app/src/main/res/values/styles.xml b/app/src/main/res/values/styles.xml
--- a/app/src/main/res/values/styles.xml
+++ b/app/src/main/res/values/styles.xml
@@ -160,4 +160,8 @@
         <item name="materialDrawerDrawCircularShadow">false</item>
     </style>
 
+    <style name="ColoredChip" parent="Widget.MaterialComponents.Chip.Choice">
+        <item name="chipBackgroundColor">@color/compound_button_color</item>
+    </style>
+
 </resources>
```

2020-11-06 18:02 UTC, Tak commented
Can the chips not just be a constant size?

I don't have a strong feeling about the position in the menu.

Should there also be a notification for new announcements?

2020-11-08 19:23 UTC, connyduck requested changes
>  Am I something wrong?

Yes, you need to set `<item name="chipStyle">` on the theme overlay style and link another style there, and in that other style you can use `chipBackground` and it will work.

2020-11-08 19:23 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementAdapter.kt
> +        private var items: List<Announcement>,
I would rather put `var items: List<Announcement> = emptyList()` into the class body

2020-11-08 19:23 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/components/announcements/AnnouncementsActivity.kt
> +        }
```suggestion
        fun newIntent(context: Context) = Intent(context, AnnouncementsActivity::class.java)
```

2020-11-08 19:23 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/entity/Announcement.kt
> +        val reactions: List<Reaction>
please always use `List` (not `Array`) in model classes

2020-11-08 19:23 UTC, connyduck commented on app/src/main/res/layout/activity_announcements.xml
> +        app:layout_behavior="@string/appbar_scrolling_view_behavior">
It should be possible to do this layout without a `ConstraintLayout`. Try putting the `app:layout_behavior="@string/appbar_scrolling_view_behavior"` on the `SwipeRefreshLayout` and center the `Progressbar` and the `BackgroundMessageView` inside the `CoordinatorLayout`.

2020-11-08 19:23 UTC, connyduck commented on app/src/main/res/layout/item_announcement.xml
> +        app:layout_constraintStart_toStartOf="parent"
Please add `android:lineSpacingMultiplier="1.1"`. Makes multiline text easier to read.

2020-11-08 19:23 UTC, connyduck commented on app/src/main/res/values/strings.xml
> +    <string name="no_announcements">There\'s no announcements.</string>
`There are no announcements.`

2020-11-09 08:05 UTC, kyori19 commented
> Yes, you need to set `<item name="chipStyle">` on the theme overlay style and link another style there, and in that other style you can use `chipBackground` and it will work.

Thanks. I understood how to apply styles.
For now, I changed to use default style, and I think this is enough to distinguish.
How do you think?
![image](https://user-images.githubusercontent.com/27999567/98515002-b9fd3d80-22ad-11eb-9c24-b225c53c5bd6.png)

2020-11-10 20:00 UTC, connyduck commented
> How do you think?

I think its fine. If you want more contrast you could make the background of the unselected one a bit darker though.

2020-11-17 19:12 UTC, connyduck commented
@kyori19 If you resolve the merge conflict I'd merge it so nightly testers can try it out.

2020-11-18 08:21 UTC, kyori19 commented
@connyduck I resolved the conflict, but now build is failing...
I didn't touch anything in dependencies... Why is this happens...?

2020-11-18 20:08 UTC, connyduck approved these changes

2020-11-18 20:09 UTC, connyduck commented
I have no idea why it happened, but for some reason it complained about not being able to resolving a dependency. Upgrading it fixed the problem.

2020-11-18 20:12 UTC, merged