multiple media upload support
tuskyapp/Tusky pull request #2029
Opened 2020-12-27 17:53 UTC by lenchan139

with this PR, now can upload multiple media with the system chooser.

If the user chooses images + uploaded images is greater than 4, then won't upload and show an error message.

2020-12-27 22:16 UTC, lenchan139 commented on app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
> +                            val imageUri: Uri = clipData.getItemAt(i).getUri()
Yes, I tried. 

Actually, for these codes, I saw and referenced the function applyShareIntent(...) on the same file that also use for-loop to import media, so I think it already works properly. 

And, I built a debug.apk and install my phone and compose some toots and still using it, it works without bugs and crashes so far.

2020-12-27 22:20 UTC, lenchan139 commented on app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeActivity.kt
> +                            val imageUri: Uri = clipData.getItemAt(i).getUri()
Yes, I tried. 

Actually, for these codes, I saw and referenced the function applyShareIntent(...) on the same file that also use for-loop to import media, so I think it already works properly. 

And, I built a debug.apk and install my phone and compose some toots and still using it, it works without bugs and crashes so far.

2020-12-28 18:35 UTC, connyduck requested changes

2020-12-28 18:35 UTC, connyduck commented on app/src/main/res/values/strings.xml
> +    <string name="error_upload_over_four_media">You cannot upload more than 4 media.</string>
I'd not add the magic number into the string
```suggestion
    <string name="error_upload_max_media_reached">You cannot upload more than %1$d media attachments.</string>
```

2020-12-30 16:35 UTC, connyduck approved these changes

2020-12-30 16:36 UTC, merged