Notifications streaming
tuskyapp/Tusky pull request #2065
Opened 2021-01-31 04:09 UTC by a1batross

Since pull notifications seems to get unreliable more and more, I decided to implement live notifications.

Currently, it's naive implementation that just starts service which just connects to instance's WebSocket. It works. After long absense of network connection, it may die but will reconnect as soon as user will open Tusky again.

Battery drain happens but it's only 1-2% over night on my phone. 🤷🏼

2021-01-31 18:27 UTC, connyduck commented
Very cool 🧐 
I will put this on my phone for a while to test it.
Can you make a dedicated database migration in the meantime, please?

2021-02-01 01:37 UTC, a1batross commented
> Can you make a dedicated database migration in the meantime, please?

Done!

2021-02-02 18:14 UTC, a1batross commented
@Tak weird. Is sticky notification is shown up? 

I have a testing accounts on mstdn.social and mastodon.ml, both on vanilla 3.3.0. It works there.

2021-02-03 08:56 UTC, Tak commented
Yeah, the sticky notification is there.

2021-02-04 18:54 UTC, connyduck requested changes
It works nicely for me, most of the time. Amazing to see real time notifications without Google stuff in Tusky. But sometimes the connection gets lost while the notification stays. I think it should either try to reconnect as long as the service runs, or kill the service and the notification as well when there is no connection.

Also, it would be nice if clicking the notifications does something, maybe just open the app.

2021-02-04 18:54 UTC, connyduck commented on app/schemas/com.keylesspalace.tusky.db.AppDatabase/25.json
> +    "identityHash": "81c19fca95f32273ff674ec67cb17e0e",
please revert the changes to this file and check in the 26.json instead

2021-02-04 18:54 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/service/StreamingService.kt
> +        private fun startForegroundService(ctx: Context, intent: Intent) {
use `ContextCompat.startForegroundService` instead

2021-02-04 18:54 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/service/StreamingService.kt
> +        val TAG = "StreamingService"
these can be `private const val`

2021-02-04 18:54 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/service/StreamingService.kt
> +        }
```suggestion
        sockets[id]?.close(1000, null)
        sockets.remove(id)
```

2021-02-04 18:54 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/service/StreamingService.kt
> +    lateinit var eventHub: EventHub
Not used?

2021-02-04 18:54 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/service/StreamingService.kt
> +        notificationManager.cancel(1337)
make that 1337 a constant please

2021-02-04 18:54 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/service/StreamingService.kt
> +        @JvmStatic
`@JvmStatic` is not needed if the method is only called from Kotlin

2022-08-03 00:58 UTC, a1batross commented
Not needed anymore with the introduction of UnifiedPush support.

2022-08-03 00:58 UTC, closed without merging