filter messages by also looking at media descriptions
tuskyapp/Tusky pull request #2285
Opened 2021-12-31 02:13 UTC by ariasuni

Fix #2284

I have not tried it yet

2022-01-03 13:00 UTC, Tak commented
Makes sense to me

2022-01-03 14:33 UTC, connyduck requested changes
Can you please extend the `FilterTest` with a testcase for this?

2022-01-03 14:33 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/network/FilterModel.kt
> +            .map { it.description as String }
```suggestion
            .mapNotNull { it.description }
```

2022-01-04 00:32 UTC, ariasuni commented
I added the test and improved the code as suggested :slightly_smiling_face:

2022-01-04 18:28 UTC, connyduck commented
Thank you!

2022-01-04 18:28 UTC, merged