Use tags from status when adding handlers to hashtag spans in status content
tuskyapp/Tusky pull request #2344
Opened 2022-02-18 14:06 UTC by Tak

Fixes #2283

2022-02-18 20:27 UTC, connyduck requested changes
😍

2022-02-18 20:27 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
> +    }
```suggestion
    builder.getSpans(0, content.length, URLSpan::class.java)
        .forEach { span ->
            setClickableText(span, builder, mentions, tags, listener)
        }
```

2022-02-18 20:27 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
> +    }
```suggestion
    return tags?.firstOrNull { it.url == span.url }?.let { tag ->
        object : NoUnderlineURLSpan(span.url) {
                        override fun onClick(view: View) = listener.onViewTag(tag.name)
        }
    }
```

(similar in other places)

2022-02-18 20:27 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
> +    val builder = SpannableStringBuilder()
There is a `buildSpannedString` top level function that would make this function a little bit easier to write https://developer.android.com/reference/kotlin/androidx/core/text/package-summary#buildSpannedString(kotlin.Function1)

It kinda sucks that it converts the result to `SpannedString` which is an additional object allocation we don't need though

2022-02-18 20:27 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
> +) {
`) = builder.apply {` maybe? Would get rid of the repeated `builder.`

2022-02-18 20:27 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
> +        text[0] == '@' -> getCustomSpanForMention(mentions, span, listener)
```suggestion
    val customSpan = when(text[0]) {
        '#' -> getCustomSpanForTag(tags, span, listener)
        '@' -> getCustomSpanForMention(mentions, span, listener)
```

2022-02-19 19:42 UTC, charlag commented on app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
> +        URI(urlString)
I would rather use java.net.URI in generic code

2022-02-21 19:28 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.kt
> + * @param context context
```suggestion
 * @receiver the Context to open the link from
```

2022-02-21 19:32 UTC, connyduck requested changes
Thanks for the changes!

I think I the non-null `tags: List<HashTag>` has to be changed again though.
Hashtags in profile bios no longer open in Tusky.

The right behavior probably is
- We have a tag list -> only open tags in Tusky that match (=what you added with this PR)
- We have no tag list (it is null) -> open all tags within Tusky (what we did before this PR)

2022-02-23 19:17 UTC, connyduck approved these changes

2022-02-25 17:56 UTC, merged