Implement reply count indicator to track web UI
tuskyapp/Tusky pull request #2467
Opened 2022-04-27 19:39 UTC by Tak

Resurrected by request

2022-04-28 19:11 UTC, connyduck requested changes
Thank you 🙏

2022-04-28 19:11 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
> +            replyCountLabel.setText((repliesCount > 1 ? replyCountLabel.getContext().getString(R.string.status_count_one_plus) : NUMBER_FORMAT.format(repliesCount)));
Is there really a need to format a 0? Like, how could it be displayed differently?

2022-04-28 19:11 UTC, connyduck commented on app/src/main/res/layout/item_status.xml
> +        android:textSize="?attr/status_text_medium" />
I think it looks best when the number is vertically centered next to the button, like this 
```suggestion
    <TextView
        android:id="@+id/status_replies"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="?attr/status_text_medium"
        app:layout_constraintBottom_toBottomOf="@id/status_reply"
        app:layout_constraintStart_toEndOf="@id/status_reply"
        app:layout_constraintTop_toTopOf="@id/status_reply" />
```

2022-04-30 08:22 UTC, Tak commented
:+1: updated

2022-05-03 17:16 UTC, connyduck approved these changes
will merge for Tusky 19

2022-05-03 20:24 UTC, Tak commented
In that case, I'll PR the fix for preview cards in timelines and rebase this one on top

2022-05-17 17:58 UTC, connyduck commented
Can you please resolve the conflicts?

2022-05-20 13:12 UTC, Tak commented
Reresolved

2022-05-20 14:47 UTC, merged