Add view for browsing and unfollowing followed hashtags
tuskyapp/Tusky pull request #2794
Opened 2022-11-09 12:16 UTC by Tak

Implements #2785

2022-11-15 18:00 UTC, connyduck commented
Can you make slightly more advanced list items with an x button (like we have in "hidden domains")?
And instead of dialog before unfollow I'd make an "undo" snackbar (also like in "hidden domains").

2022-11-16 12:37 UTC, Tak commented
Updated

2022-11-16 17:27 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/FollowedTagsActivity.kt
> +    private suspend fun refreshDisplay() {
doesn't need to be suspending

2022-11-16 18:03 UTC, connyduck approved these changes
Will merge after Tusky 20 release

2022-11-24 15:22 UTC, connyduck requested changes
Sorry to un-approve this again, but I just found out that this api is paginated, so we need to implement that as well or it won't work when a lot of hashtags are followed https://docs.joinmastodon.org/methods/followed_tags/#get

I'd to it the same as in other places with `RemoteMediator`/`PagingSource`

2022-11-24 18:28 UTC, Tak commented
Of course in 4.0.3, I'll rework it

2022-11-29 20:35 UTC, connyduck commented
Default page size is 100, how many users follow that many hashtags... I'd be ok with merging it without pagination for now as well.

2022-11-30 20:14 UTC, connyduck reviewed
It now crashes when opening the view while offline. I think you need to extend the try block in `FollowedTagsRemoteMediator`.

2022-11-30 20:14 UTC, connyduck commented on app/src/main/java/com/keylesspalace/tusky/components/followedtags/FollowedTagsViewModel.kt
> +    val tags: MutableList<HashTag> = emptyList<HashTag>().toMutableList()
```suggestion
    val tags: MutableList<HashTag> = mutableListOf()
```

2022-12-01 18:24 UTC, connyduck approved these changes

2022-12-01 18:24 UTC, merged