Status: Display indicators of edited posts
tuskyapp/Tusky pull request #2935
Opened 2022-11-25 18:40 UTC by fruyek

![Screenshot_20221125-181626](https://user-images.githubusercontent.com/119071347/204039430-e2ae8ce3-5bb5-40b2-aa87-f03caa6453f3.png)

2022-11-28 23:11 UTC, fruyek commented
> Could you please try to also add it to the accessibility description? at least in the full view (see `setDescriptionForStatus()`)

I think I already did that in https://github.com/tuskyapp/Tusky/pull/2935/commits/fcfc058ace6be7736a711076b53a53d2df8a998f. Do I have to add it somewhere else as well?

2022-11-28 23:27 UTC, charlag commented
No, it's perfect, I was tired and missed that, sorry!

2022-11-29 09:25 UTC, Gryzor commented on app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java
> +        if (editedAt != null)
I'd say if you don't mind use the brackets {} as the project uses them everywhere, even for one line if statements (at least that has been my limited experience). 

There's more instances of this, so I will not spam you with comments, but I'm sure the project maintainer will care for the consistency.

2022-12-02 18:01 UTC, connyduck requested changes
Can you please resolve the merge conflicts so I can merge it? @fruyek

2022-12-02 18:02 UTC, connyduck approved these changes

2022-12-02 21:02 UTC, fruyek commented
@connyduck done

2022-12-03 11:15 UTC, merged