Remove rxjava deletestatus
tuskyapp/Tusky pull request #3041
Opened 2022-12-11 20:57 UTC by nikclayton

2022-12-11 20:58 UTC, nikclayton commented
Note that this is a stacked PR on top of https://github.com/tuskyapp/Tusky/pull/3008, so shows additional changes.

I'll mark this as ready for review after https://github.com/tuskyapp/Tusky/pull/3008 has been merged.

2022-12-31 11:50 UTC, connyduck requested changes

2023-01-09 13:28 UTC, nikclayton commented on app/src/main/java/com/keylesspalace/tusky/usecase/TimelineCases.kt
> +        return result
Will do.

2023-01-09 14:39 UTC, nikclayton commented on app/src/main/java/com/keylesspalace/tusky/components/search/SearchViewModel.kt
> +        return runBlocking {
Done. Since the result is used I've used Deferred/async/await, which doesn't block threads.

2023-01-10 20:19 UTC, connyduck approved these changes

2023-01-10 20:20 UTC, merged