Fix ghost tap on media tab
tuskyapp/Tusky pull request #3684
Opened 2023-05-22 20:34 UTC by maxiin

In an account media tab, if there is media that was hidden due to being tagged as sensitive and the account had the "alwaysShowSensitiveMedia" set to true, the media would show revealed, but after tapping on the image nothing would happen, because the media would still try to "be revealed"
This fixes the problem caching the alwaysShowSensitiveMedia variable from the active account, is it a good solution?

2023-05-23 17:27 UTC, connyduck requested changes
Nice find!

I think for fixing this you should investigate why `AttachmentViewData.isRevealed` is false when `alwaysShowSensitiveMedia` is true.
Looks like when mapping attachments to `AttachmentViewData` the `alwaysShowSensitiveMedia` needs to be taken into account and `isRevealed` set to the correct value - right now it is just `!sensitive`. In return the check in `AccountMediaGridAdapter` might no longer be necessary.

2023-05-23 19:12 UTC, maxiin commented
Good solution, will try to change to that!

2023-05-23 20:43 UTC, maxiin commented
I got a bit confused with the injectable system since I've never used it before, but I think this is the best solution I could come up with.

2023-05-24 17:18 UTC, connyduck commented
Yes thats better!

1) Instead of having the whole `Account` as parameter to `list`, can you give it the `alwaysShowSensitiveMedia` Boolean directly? And since `list` is called from a couple of places where `alwaysShowSensitiveMedia` does not matter, you could give it a default `false` and only pass the correct value where needed (which is in `AccountMediaRemoteMediator`).
2) There is a `alwaysShowSensitiveMedia` check in `AccountMediaGridAdapter` that is no longer needed now.
3) You need to fix the code formatting so our CI checks suceeds

2023-06-03 19:39 UTC, connyduck commented
You can set a default parameter like this `fun list(status: Status, alwaysShowSensitiveMedia: Boolean = false)` then you don't need to pass it all the time `list(status)`

2023-07-07 21:48 UTC, maxiin commented
Sorry! been busy with work, forgot to check, will try to fix today

2023-07-07 22:16 UTC, maxiin commented
Fixed, was following bitrise and it failed on unit tests, but I could not replicate in my machine, is it a bitrise error?

2023-07-09 09:27 UTC, connyduck approved these changes

2023-07-09 09:28 UTC, connyduck commented
Maybe something to add to the v23 release @nikclayton?

2023-07-12 12:23 UTC, nikclayton requested changes

2023-07-12 12:23 UTC, nikclayton commented on app/src/main/java/com/keylesspalace/tusky/components/account/media/AccountMediaRemoteMediator.kt
> +                AttachmentViewData.list(status, accountManager.activeAccount?.alwaysShowSensitiveMedia ?: false)
The active account can change over the lifecycle of this object (there's a race condition between the active account changing and the object being destroyed).

The safe thing to do is add an `activeAccount` property, like

```
val activeAccount = accountManager.activeAccount!!
```

and then use it here.

2023-07-12 12:23 UTC, nikclayton commented on app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt
> +        super.viewMedia(attachmentIndex, list(status, false), view)
What's this `false` for?

2023-07-12 12:23 UTC, nikclayton commented on app/src/main/java/com/keylesspalace/tusky/viewdata/AttachmentViewData.kt
> +
```suggestion
```

2023-07-31 10:49 UTC, nikclayton commented
@maxiin Ping -- do you have time to bring this over the finish line? If not, I'm happy to make the changes and get it merged in ahead of the next release.

2023-08-06 10:08 UTC, nikclayton commented
> @nikclayton Hi, sorry! I can't work on this right now, you can take over, yes

Thanks. https://github.com/tuskyapp/Tusky/pull/3930 is your PR, with a couple of modifications. I'll get that in shortly.

2023-08-08 21:03 UTC, nikclayton commented
@maxiin Thanks for doing the vast majority of the work on this. #3930 is merged, so I'm closing this one.

2023-08-08 21:03 UTC, closed without merging